### ISSUE TITLE
HTTP 502 from Parler while fetching tags

### ISSUE THREAD

**Issue by pranithapat** [castlelemongrab/parlance#41]
I continually receive the following error if I try to pull a bigger size of parlays (e.g. #thegreatawakening).. does anyone know if this is easy to fix? I'm relatively new to all this. Thank you!

```
(node:12854) UnhandledPromiseRejectionWarning: StatusError: Bad Gateway
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@castlelemongrab/parlance/node_modules/bent/src/nodejs.js:133:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:634:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:503:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at TLSSocket.Readable.push (_stream_readable.js:217:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12854) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by castle-lemongrab** [comment]
This is definitely a server-side error coming from Parler. Is there any noticeable (e.g. minute or more) delay between the HTTP request (visible via `--verbose` on `stderr`) and the appearance of that error backtrace?

**Comment by pranithapat** [comment]
Hi @castle-lemongrab, do you have an email that I can message you at?

**Comment by castle-lemongrab** [comment]
Sure thing; you can use security at babybritain dot ltd, whether or not the correspondence is security-related.

For what it's worth, I've seen a lot of HTTP 500s and HTTP 502s during normal operation of Parler's *own* browser frontend, so I don't suspect the failure mode above is a secret at this point.
